PLATFORM=none
KUBEFLOW_REPO=/mnt/tmp/kubeflow-0.4.1
KUBEFLOW_VERSION=master
KUBEFLOW_KS_DIR=/mnt/tmp/kubeflow-0.4.1/ks_app
KUBEFLOW_DOCKER_REGISTRY=
DOCKER_REGISTRY_KATIB_NAMESPACE=
K8S_NAMESPACE=kubeflow
KUBEFLOW_PLATFORM=null